import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { AppBar, Container, Toolbar, Typography, Button, IconButton } from '@mui/material'
import Link from 'next/link'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faAnchor, faHome, faHomeAlt } from '@fortawesome/free-solid-svg-icons'
import LeftAnchor from './LeftAnchor'


export default function Layout({children}) {
  return (
    <div>
        <Head>
        <title>Gobill</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar position='static' sx={{backgroundColor: '#002244'}} id='muibar'>
          <Toolbar>
            <IconButton sx={{color: '#fff'}}>
              <LeftAnchor/>
            </IconButton>
              <Typography sx={{color: 'white', marginRight: '10px', fontWeight:'bold', fontSize: '600' }}>
                  Gobill
              </Typography>
              <Link href='/items'>
              <Button>Items</Button>
              </Link>
              <Link href='/waybill'>
              <Button>Waybills</Button>
              </Link>
          </Toolbar>
      </AppBar>
      <Container sx={{minHeight: '80vh'}}>
          {children}
      </Container>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      
    </div>
  )
}
